# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd165cbbe43641fa4f69d2d9b829c9614731950f38fc9829d72b3db8f19d88e0389ca141c5883968af6d990dc0fd885a1cce9c5bdffd46bdd6b856949194503f

test:
  secret_key_base: 1dc9bce95e852a1535dd309d587130dee11d6652eef51dee9bc60a4c100d7067644380ae42c2d5b8e3ce1a8b86911292b8571b40d0df131e0513048affbc469c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
